### ISSUE TITLE
Cuckoo authentication with moodle not working 

### ISSUE THREAD

**Issue by MarzukhAsjad** [thermitex/thermitex.github.io#1]
Hi, I love your app (Cuckoo) and have been using it for assignment deadline tracking as it's significantly better than just using the moodle app. However currently, authentication to HKU Portal is failing, I believe the reason is because recently they have set up 2FA through Microsoft Office Login. Is there any way to fix it?

**Comment by thermitex** [comment]
Hi thanks for leaving the comment here - unfortunately I have graduated from HKU and hence lost my access to Portal. I will try to fix the issue but there's no guarantee of when or whether it can be fixed. Kindly stay tuned and will let you know if any updates.

**Comment by thermitex** [comment]
2.0 now out on App Store with Moodle auth issue fixed. Closing this issue.

Cuckoo is entirely rewritten in Flutter and is now open-source:
https://github.com/thermitex/cuckoo-flutter
